import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Providers from "./providers";
import { Toaster } from "@/components/ui/sonner";
import { LogoutNotifier } from "./components/LogoutNotifier";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="h-full">
      <body
        className={`${notoSansJP.variable} antialiased min-h-screen flex flex-col`}
      >
        <Providers>
          <Toaster 
            toastOptions={{
              className: "bg-slate-800 text-white",
              style: {
                background: "#1e293b",
                color: "#fff",
              },
            }}
          />
          <LogoutNotifier />
          <Header />
          <main className="flex-1">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
